# Generated by Django 5.2 on 2025-07-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo_compatible',
            field=models.CharField(blank=True, help_text='Modelos compatibles, separados por comas.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, help_text='Ubicación física en almacén.', max_length=100, null=True),
        ),
    ]
