# Generated by Django 5.2 on 2025-07-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_modelo_compatible_producto_ubicacion_fisica'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo al que compras el repuesto.', max_digits=10),
        ),
    ]
