# Generated by Django 5.2 on 2025-09-27 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_proveedor_ordencompra_detalleordencompra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_principal',
            field=models.ForeignKey(blank=True, help_text='Proveedor principal del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_texto',
            field=models.CharField(blank=True, help_text='Campo de texto para compatibilidad (deprecated)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(decimal_places=2, help_text='Precio al que el proveedor vende este producto', max_digits=10)),
                ('es_principal', models.BooleanField(default=False, help_text='¿Es el proveedor principal para este producto?')),
                ('tiempo_entrega_dias', models.PositiveIntegerField(default=0, help_text='Días de entrega estimados')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='inventario.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_suministrados', to='inventario.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Productos - Proveedores',
                'unique_together': {('producto', 'proveedor')},
            },
        ),
    ]
