# Generated by Django 5.2 on 2025-09-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_remove_producto_proveedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
        migrations.AddField(
            model_name='factura',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='direccion_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='email_cliente',
            field=models.EmailField(blank=True, help_text='Email (opcional, principalmente para RUC)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='impuesto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='nombre_cliente',
            field=models.CharField(blank=True, help_text='Nombre del cliente o razón social', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número de cédula o RUC', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Número correlativo de factura', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_documento',
            field=models.CharField(choices=[('ninguno', 'Sin documento'), ('cedula', 'Cédula de Identidad'), ('ruc', 'RUC')], default='ninguno', max_length=10),
        ),
    ]
