# Generated by Django 5.0.7 on 2025-12-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_optimizar_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('ninguno', 'Sin documento'), ('cedula', 'Cedula de Identidad'), ('ruc', 'RUC')], default='cedula', max_length=10)),
                ('numero_documento', models.CharField(blank=True, help_text='RUC o Cedula de Identidad', max_length=30, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('total_compras', models.PositiveIntegerField(default=0)),
                ('monto_total_compras', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveIndex(
            model_name='movimiento',
            name='idx_mov_fecha',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='idx_cat_activo',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='idx_stock_bajo',
        ),
        migrations.AddField(
            model_name='factura',
            name='exonerado_iva',
            field=models.BooleanField(default=False, help_text='Si está exonerado de IVA'),
        ),
    ]
