# Generated by Django 5.0.7 on 2026-01-31 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_cliente_remove_movimiento_idx_mov_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Número de factura del proveedor', max_length=100, unique=True)),
                ('fecha_emision', models.DateField(help_text='Fecha de emisión de la factura')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se registró en el sistema')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento para pago', null=True)),
                ('tipo_factura', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Suma de todos los items', max_digits=15)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado', max_digits=15)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, help_text='IVA y otros impuestos', max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total de la factura', max_digits=15)),
                ('timbrado', models.CharField(blank=True, help_text='Número de timbrado de la factura', max_length=50, null=True)),
                ('condicion_pago', models.CharField(blank=True, help_text='Ej: 30 días, 60 días, etc.', max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('archivo_adjunto', models.CharField(blank=True, help_text='Ruta o URL del archivo escaneado de la factura', max_length=500, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('orden_compra', models.ForeignKey(blank=True, help_text='Orden de compra relacionada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_compra', to='inventario.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_compra', to='inventario.proveedor')),
                ('usuario_registro', models.ForeignKey(blank=True, help_text='Usuario que registró la factura', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura de Compra',
                'verbose_name_plural': 'Facturas de Compra',
                'ordering': ['-fecha_emision', '-numero_factura'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción adicional del item', max_length=300, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad comprada', max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario de compra', max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='cantidad * precio_unitario', max_digits=15)),
                ('lote', models.CharField(blank=True, help_text='Número de lote', max_length=100, null=True)),
                ('fecha_vencimiento_lote', models.DateField(blank=True, help_text='Fecha de vencimiento del lote', null=True)),
                ('producto', models.ForeignKey(help_text='Producto comprado', on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('factura_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.facturacompra')),
            ],
            options={
                'verbose_name': 'Detalle de Factura de Compra',
                'verbose_name_plural': 'Detalles de Facturas de Compra',
            },
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['proveedor', '-fecha_emision'], name='inventario__proveed_58e475_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['estado', '-fecha_emision'], name='inventario__estado_d67054_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacompra',
            index=models.Index(fields=['fecha_vencimiento'], name='inventario__fecha_v_641ce5_idx'),
        ),
    ]
